import os
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent.parent))

print(os.getcwd())

from SynaptiCore.Core.genFuncs import (
    add_dir_to_path, 
    load_env_file
)

add_dir_to_path(os.getcwd())
load_env_file()

from SynaptiCore.Tools.liteLM import (
                                        create_gemini_flash_2_exp_mods,
                                        create_bedrock_claude_sonnet_3_5_mods
)
from SynaptiCore.Apps.DeCypher import DeCypher 
from SynaptiCore.Core.langFuncs import pretty_state_print

from mcp.server.fastmcp import FastMCP

# Create an MCP server
mcpDeCypher = FastMCP("DeCypher")

@mcpDeCypher.tool()
def web_search(search_message: str) -> str:
    """
    Performs a web search using the DeCypher application for the given query.
    This function utilizes the DeCypher application with pre-configured language models 
    to process the search query and retrieve relevant results.
    
    Args:
        search_message (str): The search query string to be processed by DeCypher.
    
    Returns:
        str: A string representation of the search results generated by DeCypher.
    """
    language_models = create_bedrock_claude_sonnet_3_5_mods(reqs="all")
    decypherApp = DeCypher(*language_models)
    
    return str(decypherApp(search_message))


# Run the server
if __name__ == "__main__":
    print("Starting MCP mcpDeCypher Server")
    mcpDeCypher.run()